# Generated by Django 4.1.5 on 2023-01-19 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_app', '0002_account_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='accounts/'),
        ),
    ]
